Updated jobs app
redhat-beyond/Side-Hustle pull request #33
Opened 2021-12-03 22:47 UTC by assafg95

First draft of the Job class with different fields. I still need to add more tests and check if all the methods work. This PR is without the Users app and is dependent on it. Once the User PR is merged I will insert it into this PR, so for now not all the checks might work.

2021-12-03 22:53 UTC, assafg95 commented
Will fix Flake8 errors tomorrow

2021-12-04 09:44 UTC, AshkenYariv requested changes
@assafg95 Looks really good!!! The jobs model looks great, the only thing I would add is tests for the new job function: the delete job and get_job_title as well as for the snippet_discription that it actually checks that there are 3 points (...) at the end of the sentence after snipping

2021-12-04 10:01 UTC, shayakrach requested changes
@assafg95 please add WIP to the title of the PR.

Also, add a message here to merge only after #28.

2021-12-04 10:15 UTC, assafg95 commented
Please merge this PR after PR #28 is merged

2021-12-04 14:05 UTC, assafg95 commented on jobs/tests.py
> +def test_job_snippet_description(job_1):
Not completed still having problems with this test

2021-12-04 14:07 UTC, assafg95 commented
@shayakrach @AshkenYariv @yuvalk  @EdDev  Do you suggest that I add the User class so I can run my tests?

2021-12-06 07:53 UTC, shayakrach commented
@assafg95 Please rebase with the updated master in your local branch.

2021-12-06 12:29 UTC, closed without merging

2021-12-06 12:31 UTC, yuvalk commented
why?
when closing, plz add a comment explaining why this PR is no longer needed

2021-12-06 19:29 UTC, yuvalk commented
@assafg95 can you comment?

2021-12-06 19:50 UTC, assafg95 commented
There were a lot of conflicts in the rebase that were giving me problems. Also, anyways I wanted to change most of what I had there later. So to save time I decided to make a new branch from updated master.

2021-12-06 19:52 UTC, assafg95 commented
@yuvalk can I delete the branch if it is no longer relevant?

2021-12-06 20:33 UTC, yuvalk commented
> There were a lot of conflicts in the rebase that were giving me problems. Also, anyways I wanted to change most of what I had there later. So to save time I decided to make a new branch from updated master.

I dont see anything here that warrent closing the PR, you could still reuse it
but even if that the case then you probably have a new PR ?

the best thing is to reference the new pr from the old one when closing it 
`closing this in favor of #XX`

2021-12-06 20:34 UTC, yuvalk commented
> @yuvalk can I delete the branch if it is no longer relevant?

on your github fork? sure (and the local one of course)

2021-12-06 21:19 UTC, assafg95 commented
closing this in favor of #35