created register page
redhat-beyond/Side-Hustle pull request #49
Opened 2021-12-07 21:23 UTC by edenmaor

created a register html page
added a URL path for register
referred from the login page to the register page

#42 closed.

2021-12-07 22:27 UTC, shayakrach requested changes
Same comments as #47 PR (about the register page).

2021-12-08 09:14 UTC, AshkenYariv approved these changes
The code is approved! Looks like it depends on the create login page but is not a problem in my opinion, @yuvalk please approve the login page before this.

2021-12-08 13:59 UTC, edenmaor commented
> The code is approved! Looks like it depends on the create login page but is not a problem in my opinion, @yuvalk please approve the login page before this.

@AshkenYariv Hi yariv it indeed depends on the login page so that we can refer to the register page from inside the login in case someone isn't logged in yet and need to register.

2021-12-08 14:45 UTC, AshkenYariv reviewed
@edenmaor I have not too strong on HTML but I think you need in the forms to add a name value to every section we are asking a user to input so we can use that info registering a user into the DB. What do you think?

2021-12-08 14:45 UTC, AshkenYariv commented on templates/register.html
> +    <input type="text" class="form-control" id="email">
I think you should change the id

2021-12-08 14:45 UTC, AshkenYariv commented on templates/register.html
> +    <input type="text" class="form-control" id="email">
I think you should change the id here

2021-12-09 14:16 UTC, edenmaor commented on templates/register.html
> +    <input type="text" class="form-control" id="email">
fixed

2021-12-09 15:01 UTC, assafg95 approved these changes

2021-12-09 17:05 UTC, AshkenYariv approved these changes

2021-12-09 17:05 UTC, AshkenYariv commented
Approved

2021-12-09 20:26 UTC, yuvalk commented
plz squash commits

2021-12-11 11:58 UTC, edenmaor commented
@yuvalk commit was squashed and conflicts resolved. can now approve and merge PR

2021-12-12 08:11 UTC, shayakrach requested changes
Please fix login.html style.

2021-12-12 08:14 UTC, edenmaor commented
> Please login.html style.

not sure i understand the change suggestion? @shayakrach

2021-12-12 08:14 UTC, shayakrach commented
@edenmaor it is better to fetch&rebase instead of fetch&merge.

You should squash "Merge branch 'master' into registerPageFeat" commit.

2021-12-12 08:16 UTC, edenmaor commented
> @edenmaor it is better to fetch&rebase instead of fetch&merge.
> 
> You should squash "Merge branch 'master' into registerPageFeat" commit.
@shayakrach 

its not possible because i have conflicts so when i will do rebase and after that resolved conflicts i automatically needs to handle the conflicts and merge after that.

2021-12-12 08:18 UTC, shayakrach commented
> > Please login.html style.
> 
> not sure i understand the change suggestion? @shayakrach



> > Please login.html style.
> 
> not sure i understand the change suggestion? @shayakrach

Fix the redundant line spacing and the indentdation.

2021-12-12 08:26 UTC, edenmaor commented
> @edenmaor it is better to fetch&rebase instead of fetch&merge.
> 
> You should squash "Merge branch 'master' into registerPageFeat" commit.

also there is only one commit :)

2021-12-12 08:52 UTC, edenmaor commented
> Please fix login.html style.

fixed.

2021-12-12 09:17 UTC, shayakrach commented
> > @edenmaor it is better to fetch&rebase instead of fetch&merge.
> > You should squash "Merge branch 'master' into registerPageFeat" commit.
> > @shayakrach
> 
> its not possible because i have conflicts so when i will do rebase and after that resolved conflicts i automatically needs to handle the conflicts and merge after that.

OK

2021-12-12 09:18 UTC, shayakrach approved these changes

2021-12-12 16:59 UTC, assafg95 approved these changes

2021-12-13 12:32 UTC, AshkenYariv commented
@yuvalk @edenmaor @ormergi please merge this PR ASAP so we can continue to next stage.

2021-12-15 08:11 UTC, AshkenYariv requested changes
Not relevant remove this

2021-12-15 17:53 UTC, edenmaor commented
Not relevant, go to PR #58 for the register page.

2021-12-15 17:53 UTC, closed without merging