Add tests for jobs addition WIP
redhat-beyond/Side-Hustle pull request #79
Opened 2021-12-26 22:04 UTC by shayakrach

2021-12-27 16:02 UTC, assafg95 approved these changes

2021-12-27 16:34 UTC, AshkenYariv approved these changes
Approved!

2021-12-29 07:21 UTC, ormergi requested changes
Hi, please see my review on https://github.com/redhat-beyond/Side-Hustle/pull/78 first

2021-12-29 07:21 UTC, ormergi commented on conftest.py
> +    return job_data
Why wont you use `Job` class instead?

2021-12-30 19:48 UTC, ormergi commented on conftest.py
> +    return job_data
Following our discussion offline about #78 (https://github.com/redhat-beyond/Side-Hustle/pull/78#discussion_r776848574), please try to add a class method to Job that converts it to dict.

2021-12-30 19:50 UTC, ormergi requested changes
Move the fixtures you added on conftest.py to where you use them.

2021-12-30 19:52 UTC, ormergi requested changes
Please move all the fixtures you added to conftest.py to where you use them.

2021-12-30 19:52 UTC, ormergi commented on jobs/tests/test_add_job_view.py
> +        assert not form.is_valid()
I think the test is not relevant

2021-12-30 19:52 UTC, ormergi commented on jobs/tests/test_add_job_view.py
> +def test_add_valid_job(valid_job_data):
Please add another test with invalid job

2022-01-01 21:46 UTC, ormergi approved these changes

2022-01-01 21:46 UTC, merged